### ISSUE TITLE
Authentication is throwing a white screen

### ISSUE THREAD

**Issue by adamdelaney** [uiowa/signage#31]
I cannot login using Shib on any of the environments.

**Comment by mark-bennett-uiowa** [comment]
Try again. I just edited your permissions. If it still doesn’t let you in, I will re-add you. Still not sure why the white screen is happening.

Mark B

**Comment by adamdelaney** [comment]
This is for UI Healthcare Signage.

**Comment by mark-bennett-uiowa** [comment]
Ahh okay. Not sure I have access to that.

Mark B

**Comment by adamdelaney** [comment]
I think this is related to Healthcare locking down IP addresses.
